### PR TITLE
Aslone/gke docs update

### PR DESCRIPTION
**Pull request by ajslone**
This is just a simple update to the docs for the `caliban cluster job submit` command, and one minor change to the docs for `caliban cluster create`.

### CODE REVIEW

**Comment by sritchie** [comment]
Nice, 🚢  after getting the CLA bot to be happy.

**Comment by sritchie** [comment]
Oh, also, do you mind merging master here? This had gotten stuck in `requirements-dev.txt`, but it's all fixed now:

**Comment by ajslone** [comment]
@googlebot I signed it!

**Comment by sritchie** [comment]
@ajslone I rebased master, so let's see if this goes through now. Thank you!

**Pull request merged**
